---
- hosts: all
  become: true
  tasks:
    - name: Ensure python bindings for DNF5 are present (for DNF-based systems)
      ansible.builtin.package:
        name: python3-libdnf5
        state: present
      when: ansible_pkg_mgr == "dnf"
      # If this task fails because the package doesn't exist on an older DNF system (not using DNF5),
      # we ignore the error, as the main package task will then use the available DNF.
      ignore_errors: true

    - name: Install required packages
      ansible.builtin.package: # Using FQCN for clarity and best practice
        name:
          - tmux
          - git
          - podman
        state: present
        update_cache: "{{ true if ansible_os_family == 'Debian' else omit }}" # update_cache is specific to apt/Debian


    - name: Configure SSH (less secure, for testing only!)
      lineinfile:
        path: /etc/ssh/ssh_config
        line: "{{ item }}"
        state: present
      loop:
        - "StrictHostKeyChecking no"
        - "UserKnownHostsFile /dev/null"
 
    - name: Set home directory permissions
      file:
        path: /home/{{ ansible_user }}
        mode: 0755

    - name: download microshift latest RPMs from github
      include_role:
        name: microshift-okd-download

    - name: download microshift latest RPMs from github
      include_role:
        name: microshift-okd-bootc