# Containerfile to package the downloaded MicroShift asset
FROM quay.io/centos-bootc/centos-bootc:stream9

ARG ASSET_FILENAME
COPY ${ASSET_FILENAME} /opt/${ASSET_FILENAME}
ENV KUBECONFIG=/var/lib/microshift/resources/kubeadmin/kubeconfig
LABEL name="microshift-asset-image"
LABEL version="4.19.0"
LABEL description="Image containing MicroShift asset: ${ASSET_FILENAME}"
RUN dnf -y install createrepo unzip
RUN cd /opt && unzip microshift-x86_64.zip && createrepo .
RUN curl https://raw.githubusercontent.com/microshift-io/microshift/3097426c2b60528edcbc7f7f2f1d28a6cddf6c48/src/create_repos.sh | bash -s "/opt"
RUN dnf -y install microshift
